---
title: "NK project: (prelimnary) DEG analysis"
author: "Sara Wernig-Zorc"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: false
    code_folding: hide
    highlight: pygments
    theme: spacelab
    df_print: paged
params:
  input: "/home/rstudio/mnt_data/BM/"
  out: "/home/rstudio/mnt_out/NK_project/"
  data: "/home/rstudio/mnt_data/"
  nb_tumors: "/home/rstudio/mnt_nb_tumors/"
  GO_db: "/home/rstudio/mnt_resources/GSEA_GeneSetEnrichments/"
  markers: "/home/rstudio/mnt_resources/MES_ADRN/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      tidy = TRUE, 
                      error = FALSE, 
                      messages = FALSE,
                      warning = FALSE)

library(parallel)
future::plan(strategy = 'future::multicore', workers = 12)
options(future.globals.maxSize = 8 * 10^9)

source("/home/rstudio/scRNA.scATAC/R/00_NK_paper_setup.R")

print(params)
```


```{r}
bm <- readRDS(paste0(params$input,"/crinier2021/Rds/scBM_healthy_seurat_v4.Rds"))
nb <- readRDS(paste0(params$out,"Rds/fetahu2023_NK_cluster.Rds"))
```

```{r}
Idents(nb) <- nb@meta.data$sample
nb <- RenameIdents(nb, 
                    "2005_1702" = "ATRXmut_01", 
                    "2006_2684" = "sporadic_01",
                    "2014_0102" = "ctrl_01",
                    "2016_1853" = "ctrl_02",
                    "2016_2950" = "ctrl_03",
                    "2016_3924" = "ATRXmut_02",
                    "2016_4503" = "MYCNA_01",
                    "2018_1404" = "MYCNA_02",
                    "2018_1625" = "sporadic_02",
                    "2018_4252" = "ctrl_04",
                    "2018_6056" = "sporadic_03",
                    "2019_2495" = "sporadic_04",
                    "2019_5022" = "MYCNA_03",
                    "2019_5754" = "MYCNA_04",
                    "2020_1288" = "ctrl_05",
                    "2020_1667" = "sporadic_05")

nb@meta.data$patients <- Idents(nb)
```


# __DEG analysis__

<br>


```{r DEG analysis}
# Set groups  to genetic subtypes
Idents(nb) <- nb@meta.data$group.x

# Plot UMAP with 
DimPlot(nb)

#0. Normalize expression data
rna <- NormalizeData(nb)

# DEG analysis with DElegate
de_results <- DElegate::findDE(object = nb, 
                               group_column = "group.x")

# DEG analysis with Seurat
#1. Find DE features between ATRXm vs. MYCNA
ATRXm.de.MYCNA <- FindMarkers(nb, ident.1 = "II", ident.2 = "III")
ATRXm.de.MYCNA

#2. Find DE features between ATRTXm vs. sporadic
ATRXm.de.Sporadic <- FindMarkers(nb, ident.1 = "II", ident.2 = "IV")
ATRXm.de.Sporadic

#3. Find DE features between ATRTXm vs. non-DTC-infiltrated BM
ATRXm.de.Ctrl <- FindMarkers(nb, ident.1 = "II", ident.2 = "I")
ATRXm.de.Ctrl
```

Here we want to know which genes are differentially expressed in NK cells in 
ATRX deleted NB genetic subtype, compare to other genetic subtypes (MYCN amplified 
and sporadic) and in control BM.

```{r NK cells only}

metadata <- as.data.frame(nb@meta.data)

#1. DEG analysis with DElegate
de_results <- DElegate::findDE(object = nb, 
                               replicate_column = "patients",
                               compare = "all_vs_all", 
                               order_results = TRUE,
                               meta_data = metadata,
                               compare_is_ref = TRUE,
                               group_column = "group.x")

de_results
write.table(de_results, file = paste0(params$out,"/tables/DEG_ATRXvsAll_DElegate.csv"),
            sep = "\t", row.names = FALSE, col.names = TRUE)

#2. DEG analysis with Seurat
#2.1 Find DE features between ATRXm vs. MYCNA
ATRXm.de.MYCNA.NK <- FindMarkers(nb, ident.1 = "III", ident.2 = "II")
ATRXm.de.MYCNA.NK
write.table(ATRXm.de.MYCNA.NK, file = paste0(params$out,"/tables/DEG_ATRXvsMYCNA.csv"),
            sep = "\t", row.names = TRUE, col.names = TRUE)

#2.2 Find DE features between ATRTXm vs. sporadic
ATRXm.de.Sporadic.NK <- FindMarkers(nb, ident.1 = "III", ident.2 = "IV")
ATRXm.de.Sporadic.NK
write.table(ATRXm.de.Sporadic.NK, file = paste0(params$out,"/tables/DEG_ATRXvsSporadic.csv"),
            sep = "\t", row.names = TRUE, col.names = TRUE)

#2.3 Find DE features between ATRTXm vs. non-DTC-infiltrated BM
ATRXm.de.Ctrl.NK <- FindMarkers(nb, ident.1 = "III", ident.2 = "I")
ATRXm.de.Ctrl.NK
write.table(ATRXm.de.Ctrl.NK, file = paste0(params$out,"/tables/DEG_ATRXvsCtrl.csv"),
            sep = "\t", row.names = TRUE, col.names = TRUE)
```

