---
title: "NK project: snATAC-seq analysis"
author: "Dr. Sara Wernig-Zorc"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  html_document: 
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: false
    code_folding: hide
    highlight: pygments
    theme: spacelab
    df_print: paged
params:
  input_BM1: "/home/rstudio/mnt_data/CancReg/BM/crinier2021/Rds/scBM_healthy_seurat_v4.Rds"
  input_BM2: "/home/rstudio/mnt_data/CancReg/BM/yang2019/Rds/Human_BM_NK_seurat_v4.Rds"
  input_BM3: "/home/rstudio/mnt_data/CancReg/BM/Lee/disco_bone_marrow_v2.0.rds"
  input_scRNA: "/home/rstudio/mnt_out/CancReg/scRNA-seq_stage_M/results/published/data/rna_decontaminated.rds"
  out: "/home/rstudio/mnt_out/NK_project/"
  GO_db: "/home/rstudio/mnt_resources/GSEA_GeneSetEnrichments/"
  anno: "/home/rstudio/mnt_resources/"
  metadata: "/home/rstudio/mnt_out/CancReg/scRNA-seq_stage_M/results/metadata/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      tidy = TRUE, 
                      error = FALSE, 
                      messages = FALSE,
                      warning = FALSE)

library(parallel)
future::plan(strategy = 'future::multicore', workers = 80)
options(future.globals.maxSize = 80 * 10^9)
options(Seurat.object.assay.version = "v5")
print(params)
```

```{r eval=FALSE, include=FALSE}
remotes::install_github("GuangchuangYu/enrichplot")
```

```{r load project specific R packages and color code}
source("/home/rstudio/NK-NB_study/code/00_NK_paper_setup.R")
source("/home/rstudio/NK-NB_study/code/00_NK_paper_utils.R")
```

```{r eval=FALSE, include=FALSE}
# preprocessed data from Fetahu et al., 2023 publication
ATAC <- readRDS(file = "/home/rstudio/mnt_out/CancReg/snATAC-seq_stage_M/results/published/data/nblast_scopen_gene_activity_normalized_motifs_added.rds")
```

```{r eval=FALSE, include=FALSE}
DimPlot(ATAC)

Idents(ATAC) <- ATAC$new.ident

ATAC <- RenameIdents(ATAC,
             "2014_0102" = 'C1', 
             "2016_1853"	= 'C2', 
             "MF244_GNB"	= 'C3',
             "MF244_GNM"	= 'C4',
             "2018_4252" = 'C4',
             "2020_1288"	= 'C5', 
             "16_4503"	= 'M1',
        "2018_1404"	= 'M2', 
        "2019_5022"	= 'M3', 
       "2019_5754"	= 'M4',
        "2005_1702"	= 'A1', 
        "2016_3924"	= 'A2', 
       "2006_2684"	= 'S1',
        "2018_1625"	= 'S2', 
       "2018_6056"	= 'S3',
       "2019_2495"	= 'A3',
        "2020_1667"	= 'S5')

ATAC$sample <-Idents(ATAC) 
table(ATAC$sample)

ATAC$group <- NA
ATAC$group[grepl("A", ATAC$sample)] <- "ATRXmut"
ATAC$group[grepl("C", ATAC$sample)] <- "control"
ATAC$group[grepl("M", ATAC$sample)] <- "MYCNamp"
ATAC$group[grepl("S", ATAC$sample)] <- "ATRXwtMYCNwt"
ATAC$group <- as.factor(ATAC$group)

table(ATAC$group)

saveRDS(ATAC, file = paste0(params$out, "/Rds/fetahu2023_scATAC_data.Rds"))
```

```{r}
ATAC <- readRDS(file = paste0(params$out, "/Rds/fetahu2023_scATAC_data.Rds"))
```

```{r fig.height=5, fig.width=5}
SCpubr::do_DimPlot(ATAC,
                   border.color = NA,
                   plot_cell_borders = FALSE,
                                 reduction = "umap_scopen",
                                 colors.use =  COLOR_CODE_ATAC,
                                 repel = TRUE,
                   group.by = "cell_type",
                                 font.size = 18,
                                 label.size  = 18,
                                 plot.axes = FALSE,
                                 label = FALSE,
                                 legend.title = "Clusters",
                                 plot.title = "",
                                 legend.position = "none")
```

```{r fig.height=5, fig.width=10}
DensityScatter(ATAC,
               x = 'nCount_peaks', 
               y = 'TSS.enrichment', 
               log_x = TRUE,
               quantiles = TRUE)

VlnPlot(
  object = ATAC,
  features = c('nCount_peaks', 
               'TSS.enrichment', 
               'blacklist_ratio', 
               'nucleosome_signal', 
               'pct_reads_in_peaks'),
  pt.size = 0.3,
  group.by = "cell_type",
  split.by = "group",
  ncol = 5)

ATAC <- subset(
  x = ATAC,
  subset = 
    pct_reads_in_peaks > 40 &
    blacklist_ratio < 0.005 &
    nucleosome_signal < 1.5 &
    TSS.enrichment < 10 &
    TSS.enrichment > 3)

DensityScatter(ATAC,
               x = 'nCount_peaks', 
               y = 'TSS.enrichment', 
               log_x = TRUE,
               quantiles = TRUE)

VlnPlot(
  object = ATAC,
  features = c('nCount_peaks', 
               'TSS.enrichment', 
               'blacklist_ratio', 
               'nucleosome_signal', 
               'pct_reads_in_peaks'),
  pt.size = 0.3,
  group.by = "cell_type",
  split.by = "group",
  ncol = 5)
```
```{r fig.height=10, fig.width=10}

UMAP_plot_byGroup <- SCpubr::do_DimPlot(ATAC,
                   border.color = NA,
                   plot_cell_borders = FALSE,
                   reduction = "umap_scopen",
                   colors.use =  COLOR_CODE_ATAC,
                   repel = TRUE,
                   group.by = "cell_type",
                   font.size = 18,
                   label.size  = 18,
                   plot.axes = FALSE,
                   label = FALSE,
                   legend.title = "Clusters",
                   plot.title = "",
                   legend.position = "none",
                   pt.size = 2,
                   split.by = "group")


UMAP_plot_byGroup

pdf(paste0(params$out,"/figures/snATAC_UMAP_splitByGroup.pdf"),
    height = 10, width = 15)
UMAP_plot_byGroup
dev.off()


png(paste0(params$out,"/figures/snATAC_UMAP_splitByGroup.png"))
UMAP_plot_byGroup
dev.off()
```

```{r}
library(reshape2)
percent_group <- table(ATAC$cell_type,ATAC$group)

# remove NB cells
percent_group <- percent_group[-6,]

# Transform this data in %
data_percentage <- apply(percent_group, 2, 
                         function(x){x*100/sum(x,na.rm=T)})

percent_group_trans <- melt(data_percentage) 

barplot_groups <- ggplot(percent_group_trans, aes(x = Var2, 
                                                      y = value, 
                                                      fill = Var1)) + 
  geom_bar(stat = "identity", position = "stack") +
  theme_void() + 
  labs(x = "", y = "Percentage of cells assigned to each cluster", 
       fill = "Clusters") +  
  ggtitle("snATAC-seq: Stacked barplot of cell types") +
  theme_minimal() +
  scale_fill_manual(values = COLOR_CODE_ATAC)

barplot_groups

pdf(paste0(params$out,"figures/barplot_ATACseq_all_clusters_per_group.pdf"))
barplot_groups
dev.off()
```

```{r}
percent_sample <- table(ATAC$cell_type,ATAC$sample)

# remove NB cells
percent_sample <- percent_sample[-6,]

# Transform this data in %
data_percentage <- apply(percent_sample, 2, 
                         function(x){x*100/sum(x,na.rm=T)})

percent_sample_trans <- melt(data_percentage) 

barplot_samples <- ggplot(percent_sample_trans, aes(x = Var2, 
                                                      y = value, 
                                                      fill = Var1)) + 
  geom_bar(stat = "identity", position = "stack") +
  theme_void() + 
  labs(x = "", y = "Percentage of cells assigned to each cluster", 
       fill = "Clusters") +  
  ggtitle("snATAC-seq: Stacked barplot of cell types") +
  theme_minimal() +
  scale_fill_manual(values = COLOR_CODE_ATAC)

barplot_samples

pdf(paste0(params$out,"figures/barplot_ATACseq_all_clusters_per_sample.pdf"))
barplot_samples
dev.off()
```

```{r eval=FALSE, include=FALSE}
Idents(ATAC) <- ATAC$cell_type

NK_ATAC <- subset(ATAC, 
                  idents = "NKT", 
                  invert = FALSE)

NK_ATAC$group <- factor(NK_ATAC$group, levels=GROUP_ORDER)

saveRDS(NK_ATAC, file = paste0(params$out, "/Rds/fetahu2023_scATAC_NK.Rds"))
```

```{r eval=FALSE, include=FALSE}
NK_ATAC <- readRDS(file = paste0(params$out, "/Rds/fetahu2023_scATAC_NK.Rds"))
```

```{r eval=FALSE, include=FALSE}
Idents(NK_ATAC) <- NK_ATAC$sample
DimPlot(NK_ATAC,
        group.by = "group")
```

```{r eval=FALSE, include=FALSE}
set.seed(2805)

DensityScatter(NK_ATAC,
               x = 'nCount_peaks', 
               y = 'TSS.enrichment', 
               log_x = TRUE, 
               quantiles = TRUE)

VlnPlot(
  object = NK_ATAC,
  features = c('nCount_peaks', 
               'TSS.enrichment', 
               'blacklist_ratio', 
               'nucleosome_signal', 
               'pct_reads_in_peaks'),
  pt.size = 0.3,
  ncol = 5)

NK_ATAC <- subset(
  x = NK_ATAC,
  subset = nCount_peaks > 1500 &
    nCount_peaks < 30000 &
    pct_reads_in_peaks > 50 &
    blacklist_ratio < 0.002 &
    nucleosome_signal < 1.5 &
    TSS.enrichment > 2)


NK_ATAC <- RunTFIDF(NK_ATAC)
NK_ATAC <- FindTopFeatures(NK_ATAC, 
                          min.cutoff = '10')
NK_ATAC <- RunSVD(NK_ATAC)
DepthCor(NK_ATAC)

NK_ATAC <- RunUMAP(object = NK_ATAC, reduction = 'lsi', dims = 2:30)
NK_ATAC <- FindNeighbors(object = NK_ATAC, 
                         reduction = 'scOpen', 
                         dims = 2:30)
NK_ATAC <- FindClusters(object = NK_ATAC, 
                        verbose = FALSE, 
                        resolution = 0.2,
                        algorithm = 3)
DimPlot(object = NK_ATAC, 
        label = TRUE) + NoLegend()

table(NK_ATAC$seurat_clusters)
Idents(NK_ATAC) <- NK_ATAC$seurat_clusters

NK_ATAC <- subset(NK_ATAC, 
                  idents = c("0","1","2"))

DimPlot(object = NK_ATAC, 
        label = TRUE) + NoLegend()

NK_ATAC$seurat_clusters <- droplevels(NK_ATAC$seurat_clusters)
```

```{r eval=FALSE, include=FALSE}
saveRDS(NK_ATAC, file = paste0(params$out, "/Rds/fetahu2023_scATAC_NK_processed.Rds"))
```

```{r}
NK_ATAC <- readRDS(file = paste0(params$out, "/Rds/fetahu2023_scATAC_NK_processed.Rds"))
```

```{r}
library(reshape2)

Idents(NK_ATAC) <- NK_ATAC$seurat_clusters

NK_ATAC$group <- as.factor(NK_ATAC$group)
NK_ATAC$seurat_clusters <- as.factor(NK_ATAC$seurat_clusters)
percent_group <- table(NK_ATAC$seurat_clusters, NK_ATAC$group)

# Transform this data in %
data_percentage <- apply(percent_group, 2, 
                         function(x){x*100/sum(x,na.rm=T)})

percent_group_trans <- melt(data_percentage) 

COLOR_CODE_BAR_PLOT <- c("0" = "#0A369D",
                         "1" = "#8AB17D",
                         "2" = "#E05263")

ggplot(percent_group_trans, aes(x = Var2, y = value, fill = Var1)) + 
  geom_bar(stat = "identity", position = "stack") +
  theme_void() + 
  labs(x = "", y = "Percentage of NK cells assigned to each sub-cluster", 
       fill = "NK clusters") +  
  ggtitle("Clustered Stacked Bar Plot of NK Groups") +
  theme(axis.text.x = element_text(angle = 0, 
                                   color = "black",
                                   size = 16),
        axis.text.y = element_text(angle = 0, 
                                   hjust = 1,
                                   color = "black",
                                   size = 16),
        legend.text = element_text(angle = 0, 
                                   hjust = 1,
                                   color = "black",
                                   size = 18),
        axis.title.x = element_text(size = 16,
                                    color = "black",),                        
        axis.title.y = element_text(size = 16,
                                    color = "black",angle = 90),                 
        legend.title = element_text(size = 16,
                                    color = "black"),
        title = element_text(size = 20,
                                    color = "black")) 
```

```{r}
library(epiAneufinder)
epiAneufinder(input = "/home/rstudio/mnt_out/CancReg/snATAC-seq_stage_M/results/published/data/AGGR_ALL_ATAC/fragments.tsv", 
              outdir = paste0(params$out), 
              blacklist = paste0("/home/rstudio/mnt_resources/",
                                 "hg38-blacklist.v2.bed"),
              windowSize = 1e5, 
              genome = "BSgenome.Hsapiens.UCSC.hg38", 
              exclude = c('chrX','chrY','chrM'), 
              reuse.existing = FALSE,
              title_karyo = "Karyogram", 
              ncores = 32,
              minFrags = 50, # 20154 cells remain with 50
              threshold_cells_nbins = 0.01,
              minsizeCNV = 0,
              k = 2,
              plotKaryo = TRUE)
```


```{r eval=FALSE, include=FALSE}
# there was an issue with the index of the fragment file
# so i loaded the original file and subset it to the NK cells only
# than loaded the subset file to the seurat object

library(data.table)

frag_file <-"/home/rstudio/mnt_out/snATAC-seq_stage_M/results/published/data/AGGR_ALL_ATAC/fragments.tsv.gz"
output_frag_file <- paste0(params$out,"Rds/feathu2023_ATAC_NKcells_fragments.tsv")

# Get the cell barcodes from the subsetted Seurat object
subset_barcodes <- colnames(NK_ATAC)

# Read the original fragment file, filter it, and write a new one
fragments <- fread(cmd = paste("zcat", frag_file), sep = "\t", header = FALSE)

# Ensure correct format: Fragment files should have 5 columns (chromosome, start, end, barcode, count)
colnames(fragments) <- c("chr", "start", "end", "barcode", "count")

# Filter for barcodes in the subsetted Seurat object
subset_fragments <- fragments[fragments$barcode %in% subset_barcodes]

# Write to a new gzipped fragment file
fwrite(subset_fragments, file = output_frag_file, sep = "\t", col.names = FALSE)
```

```{bash eval=FALSE, include=FALSE}
# Compress the file using bgzip
bgzip output_frag_file

# index file
tabix -p bed feathu2023_ATAC_NKcells_fragments.tsv.gz
```

```{r}
output_frag_file <- paste0(params$out,"Rds/feathu2023_ATAC_NKcells_fragments.tsv.gz")

fragments <- CreateFragmentObject(
  path = output_frag_file,
  cells = colnames(NK_ATAC))

NK_ATAC[['peaks']]@fragments <- list(fragments)
```

```{r}
# extrapolating RNA activity based on chromatin accessibility of the corresponding promoter regions
gene.activities <- GeneActivity(NK_ATAC)

# add the gene activity matrix to the Seurat object as a new assay and normalize it
NK_ATAC[['RNA']] <- CreateAssayObject(counts = gene.activities)
NK_ATAC <- NormalizeData(
  object = NK_ATAC,
  assay = 'RNA',
  normalization.method = 'LogNormalize',
  scale.factor = median(NK_ATAC$nCount_RNA)
)
```

```{r}
DefaultAssay(NK_ATAC) <- 'RNA'

FeaturePlot(
  object = NK_ATAC,
  features = c("ZEB2","KLF2"),
  pt.size = 0.3,
  max.cutoff = 'q25',
  ncol = 2)
```

```{r fig.height=20, fig.width=20}
FeaturePlot(
  object = NK_ATAC,
  features = TFs,
  pt.size = 0.3,
  max.cutoff = 'q75',
  ncol = 4)
```

# ___Differentially accessible peaks between NK sub-types___

```{r}
# change back to working with peaks instead of gene activities
DefaultAssay(NK_ATAC) <- 'peaks'

# wilcox is the default option for test.use
da_peaks_0vs1 <- FindMarkers(
  object = NK_ATAC,
  ident.1 = "0",
  ident.2 = "1",
  test.use = 'wilcox',
  min.pct = 0.1
)

head(da_peaks_0vs1)
```

```{r}
da_peaks_1vs2 <- FindMarkers(
  object = NK_ATAC,
  ident.1 = "1",
  ident.2 = "2",
  test.use = 'wilcox',
  min.pct = 0.1
)

head(da_peaks_1vs2)
```

```{r}
da_peaks_0vs2 <- FindMarkers(
  object = NK_ATAC,
  ident.1 = "0",
  ident.2 = "2",
  test.use = 'wilcox',
  min.pct = 0.1
)

head(da_peaks_0vs2)
```

```{r}
saveRDS(NK_ATAC, file = paste0(params$out, "/Rds/fetahu2023_scATAC_NK_processed.Rds"))
```

# ___TF Footprinting___

```{r}
NK_ATAC <- readRDS(file = paste0(params$out, "/Rds/fetahu2023_scATAC_NK_processed.Rds"))
```

## ___Generate pseudobulk coverage files per group___

```{r}
# Create meta-clusters
NK_ATAC$group <- as.character(NK_ATAC$sample)
table(NK_ATAC$group)

Idents(NK_ATAC) <- NK_ATAC$group

# Annotate groups
NK_ATAC$group[grepl("^C", NK_ATAC$group)] <- "control"
NK_ATAC$group[grepl("^M", NK_ATAC$group)] <- "MYCNamp"
NK_ATAC$group[grepl("^A", NK_ATAC$group)] <- "ATRXdel"
NK_ATAC$group[grepl("^S", NK_ATAC$group)] <- "ATRXwtMYCNwt"

NK_ATAC$group <- factor(NK_ATAC$group, levels = GROUP_ORDER)
NK_ATAC$group <- droplevels(NK_ATAC$group)
table(NK_ATAC$group)
```


## ___Generate pseudobulk coverage files per NK cluster___

```{r}
NK_ATAC_CTRL <-
  subset(ATAC_NK, idents = "control")

NK_ATAC_MYCN <-
  subset(ATAC_NK, idents = "MYCNamp")

NK_ATAC_ATRX <-
  subset(ATAC_NK, idents = "ATRXmut")

NK_ATAC_WT <-
  subset(ATAC_NK, idents = "ATRXwtMYCNwt")

frag_path <- "/home/root/mnt_out/NK_project/Rds/feathu2023_ATAC_NKcells_fragments.tsv.gz"
```

```{r export function v1}
ExportGroupBigWigs <- function(
    seurat_obj,
    group.by,
    genome = "hg38",
    min_score = 1,
    output_dir = "bigwig_output") {
    library(Signac)
    library(GenomicRanges)
    library(rtracklayer)
    library(Seurat)
    library(data.table)
  
    if (length(Fragments(seurat_obj)) == 0) {
      stop("No fragment object found in Seurat object.")
    }
  
    frag_path <- Fragments(seurat_obj)[[1]]@path
  
    if (!file.exists(frag_path)) {
      stop("Fragment file does not exist: ", frag_path)
    }
  
    if (!dir.exists(output_dir)) {
      dir.create(output_dir, recursive = TRUE)
    }
  
    groups <- unique(seurat_obj@meta.data[[group.by]])
  
    for (grp in groups) {
      message("Processing group: ", grp)
      group_cells <- colnames(seurat_obj)[seurat_obj@meta.data[[group.by]] == grp]
  
      # Read in fragments and filter by cell barcodes
      message("Reading fragment file (this may take a bit)...")
      frag_dt <- fread(
        frag_path,
        select = c(1, 2, 3, 4),
        col.names = c("chr", "start", "end", "cell"),
        showProgress = FALSE
      )
  
      frag_dt <- frag_dt[cell %in% group_cells]
  
      if (nrow(frag_dt) == 0) {
        warning("No fragments found for group: ", grp)
        next
      }
  
      gr <- GRanges(
        seqnames = frag_dt$chr,
        ranges = IRanges(start = frag_dt$start, end = frag_dt$end)
      )
  
      # Compute coverage
      cov <- coverage(gr)
      cov_gr <- as(cov, "GRanges")
  
      # Filter low coverage
      if (!is.null(min_score)) {
        cov_gr <- cov_gr[cov_gr$score >= min_score]
      }
  
      # Add genome info
      seqinfo(cov_gr) <- Seqinfo(genome = genome)
  
      # Export BigWig
      out_file <- file.path(output_dir, paste0("NK_ATAC_",grp, ".bw"))
      export(cov_gr, out_file, format = "BigWig")
  
      message("Exported BigWig: ", out_file)
    }
  
    message("Files saved in: ", normalizePath(output_dir))
  }

```

```{r export function v2}
ExportGroupBigWigs <- function(
    seurat_obj,
    group.by,
    genome = "hg38",
    min_score = 1,
    output_dir = "bigwig_output",
    frag_path = NULL) {

    library(Signac)
    library(GenomicRanges)
    library(rtracklayer)
    library(Seurat)
    library(data.table)
    library(GenomeInfoDb)
  
    if (is.null(frag_path)) {
      if (length(Fragments(seurat_obj)) == 0) {
        stop("No fragment object found in Seurat object.")
      }
      frag_path <- Fragments(seurat_obj)[[1]]@path
    }
  
    if (!file.exists(frag_path)) {
      stop("Fragment file does not exist: ", frag_path)
    }

    if (!dir.exists(output_dir))
        dir.create(output_dir, recursive = TRUE)

    groups <- unique(seurat_obj@meta.data[[group.by]])

    # Read fragments once
    frag_all <- fread(
        frag_path,
        select = c(1,2,3,4),
        col.names = c("chr","start","end","cell")
    )

    # load genome seqinfo
    library(BSgenome.Hsapiens.UCSC.hg38)
    si <- seqinfo(BSgenome.Hsapiens.UCSC.hg38)
    seqinfo(cov_gr) <- si[names(seqinfo(cov_gr))]

    for (grp in groups) {
        cells <- colnames(seurat_obj)[seurat_obj@meta.data[[group.by]] == grp]

        frag_dt <- frag_all[cell %in% cells]
        if (nrow(frag_dt) == 0) next

        gr <- GRanges(
            seqnames = frag_dt$chr,
            ranges = IRanges(frag_dt$start, frag_dt$end)
        )

        cov <- coverage(gr)
        cov_gr <- as(cov, "GRanges")

        if ("score" %in% colnames(mcols(cov_gr)))
            cov_gr <- cov_gr[cov_gr$score >= min_score]

        seqinfo(cov_gr) <- si[names(seqinfo(cov_gr))]

        sample_name <- seurat_obj@project.name
        out_file <- file.path(output_dir, paste0(sample_name, "_", grp, ".bw"))

        export(cov_gr, out_file, format = "BigWig")
    }
}
```

```{r}
sample.list <- list(NK_ATAC_CTRL,NK_ATAC_MYCN,NK_ATAC_ATRX,NK_ATAC_WT)

# export per group per NK subset

for (sample in sample.list){
  Idents(sample) <- sample$seurat_clusters
  ExportGroupBigWigs(
  seurat_obj = sample,
  group.by = "seurat_clusters",
  genome = "hg38",          
  min_score = 5,       #  filter for low signal
  frag_path  = "/home/root/mnt_out/NK_project/Rds/feathu2023_ATAC_NKcells_fragments.tsv.gz",
  output_dir = paste0(params$out,"Rds/bigwigs/")
)
}
```

```{r}
# export per group

ExportGroupBigWigs(
  seurat_obj = NK_ATAC,
  group.by = "group",
  genome = "hg38",          
  min_score = 5,       #  filter for low signal
  output_dir = paste0(params$out,"Rds/bigwigs/")
)
```

# ___TF footprinting in NK cells___

## ___ZEB2 motif___

```{r fig.height=6, fig.width=9}
library(GenomicRanges)
library(rtracklayer)
library(BSgenome.Hsapiens.UCSC.hg38)
library(Biostrings)
library(ggplot2)
library(tidyr)
library(dplyr)
library(TFBSTools)

# custom motif matrix for ZEB2 TF (from HOMER)
zeb2_pfm <- matrix(c(
  0.210, 0.136, 0.489, 0.166,
  0.172, 0.247, 0.306, 0.275,
  0.368, 0.242, 0.218, 0.171,
  0.001, 0.965, 0.001, 0.033,
  0.997, 0.001, 0.001, 0.001,
  0.001, 0.001, 0.997, 0.001,
  0.001, 0.001, 0.997, 0.001,
  0.001, 0.001, 0.001, 0.997,
  0.137, 0.001, 0.861, 0.001,
  0.276, 0.050, 0.123, 0.551,
  0.178, 0.242, 0.546, 0.034,
  0.070, 0.498, 0.200, 0.232), 
  nrow = 4, byrow = TRUE,
  dimnames = list(c("A", "C", "G", "T"), NULL))

# create PFMatrix from matrix
zeb2_pwm <- PFMatrix(
  ID = "ZEB2",
  name = "ZEB2",
  matrixClass = "PWM",
  strand = "+",
  bg = c(A = 0.25, C = 0.25, G = 0.25, T = 0.25),
  profileMatrix = zeb2_pfm
)

# input bigwigs
group_names <- unique(NK_ATAC$group)  # sample IDs
bw_files <- paste0(params$out,"Rds/bigwigs/",group_names,".bw")   # assumes filenames like A1.bw etc.
motif_name <- "ZEB2"
flank <- 100  # 100bp upstream/downstream of motif center (or less???)
genome <- BSgenome.Hsapiens.UCSC.hg38

# find motif locations
match_custom_motif <- function(pwm, genome, min.score = "85%") {
  hits <- matchPWM(pwm, genome, min.score = min.score)
  gr <- as(hits, "GRanges")
  seqlevelsStyle(gr) <- "UCSC"
  return(gr)
}

# sanitiy check
zeb2_pfm

motif_gr <- match_custom_motif(zeb2_pfm, genome)

# Keep only canonical chromosomes
keep_chr <- paste0("chr", c(1:22, "X", "Y"))
motif_gr <- motif_gr[seqnames(motif_gr) %in% keep_chr]

# sanity check to see if only canonical chromosomes are kept
table(seqnames(motif_gr) %in% keep_chr)

# center motifs
motif_center <- resize(motif_gr, 1, fix = "center")
windows <- resize(motif_center, width = flank * 2 + 1, fix = "center")

# extract coverage around motifs for each group
get_footprint <- function(bw_file, windows, flank) {
  bw <- import(BigWigFile(bw_file), which = windows, as = "RleList")
  cov_matrix <- matrix(nrow = length(windows), ncol = flank * 2 + 1)
  
  for (i in seq_along(windows)) {
    region <- windows[i]
    chr <- as.character(seqnames(region))
    cov <- bw[[chr]][start(region):end(region)]
    cov_matrix[i, ] <- as.numeric(cov)
  }
  
  avg <- colMeans(cov_matrix, na.rm = TRUE)
  return(avg)
}

# loop over groups and build dataframe(s)
footprints <- lapply(seq_along(bw_files), function(i) {
  signal <- get_footprint(bw_files[i], windows, flank)
  data.frame(
    position = -flank:flank,
    accessibility = signal,
    group = group_names[i]
  )
})

footprints_df <- do.call(rbind, footprints)

# Differential TF footprinting plot 
ggplot(footprints_df, aes(x = position, y = accessibility, color = group)) +
  geom_line(size = 1.2) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
  theme_minimal(base_size = 18) +
  labs(
    title = paste("ZEB2 Footprinting in NK cells, across groups"),
    subtitle = "Aggregate scATAC-seq signal around motif centers (±100 bp)",
    x = "Position relative to motif center [bp]",
    y = "Mean accessibility (BigWig signal)",
    color = "Group"
  ) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank()
  ) + 
  scale_color_manual(values = COLOR_CODE_GROUP_v4) 
```

```{r}
install.packages("ggpubr")  # for stat_compare_means

library(ggpubr)

# Extract position 0 values for stats
center_values <- footprints_df %>% dplyr::filter(position == 0)

# Optional: define pairwise comparisons
comparisons <- combn(unique(center_values$group), 2, simplify = FALSE)

# Plot with stats and export
p <- ggplot(footprints_df, aes(x = position, y = accessibility, color = group)) +
  geom_line(size = 1.2) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
  theme_minimal(base_size = 14) +
  labs(
    title = paste("ZEB2 Footprinting across Conditions"),
    subtitle = "Aggregate ATAC-seq signal around motif centers (±100 bp)",
    x = "Position relative to motif center (bp)",
    y = "Mean accessibility (BigWig signal)",
    color = "Group"
  ) +
  scale_color_manual(values = COLOR_CODE_GROUP_v4) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank()
  )

# Create stats bar plot for accessibility at motif center
p_stat <- ggplot(center_values, aes(x = group, y = accessibility, fill = group)) +
  geom_boxplot(width = 0.6, alpha = 0.8) +
  stat_compare_means(comparisons = comparisons, method = "t.test") +
  scale_fill_manual(values = COLOR_CODE_GROUP_v4) +
  labs(
    title = "ZEB2 Motif Accessibility at Footprint Center",
    y = "Accessibility (BigWig signal at position 0)", x = NULL
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")

# Save both plots
ggsave(paste0(params$out,"figures/ZEB2_TF_footprint_plot.pdf"), 
       plot = p, width = 7, height = 5, dpi = 600)
ggsave(paste0(params$out,"ZEB2_footprint_center_stats.pdf"), 
       plot = p_stat, width = 6, height = 5, dpi = 600)

```

```{r}
install.packages("patchwork")

# --- Combine and export ---
combined_plot <- p / p_stat + plot_layout(heights = c(2, 1))

ggsave(paste0(params$out,"ZEB2_footprint_combined.pdf"), 
       plot = combined_plot,
       width = 7, height = 9, 
       dpi = 600, device = cairo_pdf)
```


## ___STAT5 motif___


```{r fig.height=6, fig.width=9}
library(GenomicRanges)
library(rtracklayer)
library(BSgenome.Hsapiens.UCSC.hg38)
library(Biostrings)
library(ggplot2)
library(tidyr)
library(dplyr)
library(TFBSTools)

# custom motif matrix for STAT5 TF (from HOMER)
STAT5_pfm <- matrix(c(
0.379,	0.156,	0.238,	0.227,
0.163,	0.196,	0.203,	0.438,
0.001,	0.001,	0.001	, 0.997,
0.001,	0.001,	0.001,	0.997,
0.001,	0.997,	0.001,	0.001,
0.008,	0.312,	0.001,	0.679,
0.273,	0.219,	0.224,	0.284,
0.694,	0.001,	0.297,	0.008,
0.001,	0.001,	0.997,	0.001,
0.997,	0.001,	0.001,	0.001,
0.997,	0.001,	0.001,	0.001,
0.44,	0.187,	0.208,	0.165), 
  nrow = 4, byrow = TRUE,
  dimnames = list(c("A", "C", "G", "T"), NULL))

# create PFMatrix from matrix
STAT5_pwm <- PFMatrix(
  ID = "STAT5",
  name = "STAT5",
  matrixClass = "PWM",
  strand = "+",
  bg = c(A = 0.25, C = 0.25, G = 0.25, T = 0.25),
  profileMatrix = STAT5_pfm
)

# input bigwigs
#group_names <- unique(NK_ATAC$group)  # sample IDs
group_names <- GROUP_ORDER
bw_files <- paste0(params$out,"Rds/bigwigs/",group_names,".bw")   # assumes filenames like A1.bw etc.
motif_name <- "STAT5"
flank <- 20  # 100bp upstream/downstream of motif center (or less???)
genome <- BSgenome.Hsapiens.UCSC.hg38

# find motif locations
match_custom_motif <- function(pwm, genome, min.score = "85%") {
  hits <- matchPWM(pwm, genome, min.score = min.score)
  gr <- as(hits, "GRanges")
  seqlevelsStyle(gr) <- "UCSC"
  return(gr)
}

# sanitiy check
STAT5_pfm

motif_gr <- match_custom_motif(STAT5_pfm, genome)

# Keep only canonical chromosomes
keep_chr <- paste0("chr", c(1:22, "X", "Y"))
motif_gr <- motif_gr[seqnames(motif_gr) %in% keep_chr]

# sanity check to see if only canonical chromosomes are kept
table(seqnames(motif_gr) %in% keep_chr)

# center motifs
motif_center <- resize(motif_gr, 1, fix = "center")
windows <- resize(motif_center, width = flank * 2 + 1, fix = "center")

# extract coverage around motifs for each group
get_footprint <- function(bw_file, windows, flank) {
  bw <- import(BigWigFile(bw_file), which = windows, as = "RleList")
  cov_matrix <- matrix(nrow = length(windows), ncol = flank * 2 + 1)
  
  for (i in seq_along(windows)) {
    region <- windows[i]
    chr <- as.character(seqnames(region))
    cov <- bw[[chr]][start(region):end(region)]
    cov_matrix[i, ] <- as.numeric(cov)
  }
  
  avg <- colMeans(cov_matrix, na.rm = TRUE)
  return(avg)
}

# loop over groups and build dataframe(s)
footprints <- lapply(seq_along(bw_files), function(i) {
  signal <- get_footprint(bw_files[i], windows, flank)
  data.frame(
    position = -flank:flank,
    accessibility = signal,
    group = group_names[i]
  )
})

footprints_df <- do.call(rbind, footprints)

# Differential TF footprinting plot 
ggplot(footprints_df, aes(x = position, y = accessibility, color = group)) +
  geom_line(size = 1.2) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
  theme_minimal(base_size = 18) +
  labs(
    title = paste("STAT5 Footprinting in NK cells, across groups"),
    subtitle = "Aggregate scATAC-seq signal around motif centers (±100 bp)",
    x = "Position relative to motif center [bp]",
    y = "Mean accessibility (BigWig signal)",
    color = "Group"
  ) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank()
  ) + 
  scale_color_manual(values = COLOR_CODE_GROUP_v4) 
```

```{r}
#install.packages("ggpubr")  # for stat_compare_means

library(ggpubr)

# Extract position 0 values for stats
center_values <- footprints_df %>% dplyr::filter(position == 0)

# Optional: define pairwise comparisons
comparisons <- combn(unique(center_values$group), 2, simplify = FALSE)

# Plot with stats and export
p <- ggplot(footprints_df, aes(x = position, y = accessibility, color = group)) +
  geom_line(size = 1.2) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
  theme_minimal(base_size = 14) +
  labs(
    title = paste("STAT5 Footprinting across Conditions"),
    subtitle = "Aggregate ATAC-seq signal around motif centers (±100 bp)",
    x = "Position relative to motif center (bp)",
    y = "Mean accessibility (BigWig signal)",
    color = "Group"
  ) +
  scale_color_manual(values = COLOR_CODE_GROUP_v4) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank()
  )

# Create stats bar plot for accessibility at motif center
p_stat <- ggplot(center_values, aes(x = group, y = accessibility, fill = group)) +
  geom_boxplot(width = 0.6, alpha = 0.8) +
  stat_compare_means(comparisons = comparisons, method = "t.test") +
  scale_fill_manual(values = COLOR_CODE_GROUP_v4) +
  labs(
    title = "STAT5 Motif Accessibility at Footprint Center",
    y = "Accessibility (BigWig signal at position 0)", x = NULL
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")

# Save both plots
ggsave(paste0(params$out,"figures/STAT5_TF_footprint_plot.pdf"), 
       plot = p, width = 7, height = 5, dpi = 600)
ggsave(paste0(params$out,"STAT5_footprint_center_stats.pdf"), 
       plot = p_stat, width = 6, height = 5, dpi = 600)

```

```{r}
#install.packages("patchwork")

# --- Combine and export ---
combined_plot <- p / p_stat + plot_layout(heights = c(2, 1))
combined_plot
ggsave(paste0(params$out,"STAT5_footprint_combined.pdf"), 
       plot = combined_plot,
       width = 7, height = 9, 
       dpi = 600, device = cairo_pdf)
```


## ___TBX21 motif___