---
title: "NK project: Sensitivity analysis"
author: "Dr. Sara Wernig-Zorc"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  html_document: 
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: false
    code_folding: hide
    highlight: pygments
    theme: spacelab
    df_print: paged
params:
  input_BM1: "/home/rstudio/mnt_data/CancReg/BM/crinier2021/Rds/scBM_healthy_seurat_v4.Rds"
  input_BM2: "/home/rstudio/mnt_data/CancReg/BM/yang2019/Rds/Human_BM_NK_seurat_v4.Rds"
  input_BM3: "/home/rstudio/mnt_data/CancReg/BM/Lee/disco_bone_marrow_v2.0.rds"
  input_scRNA: "/home/rstudio/mnt_out/NK_project/Rds/fetahu2023_withNewMetadata.Rds"
  input_NK: "/home/rstudio/mnt_out/NK_project/Rds/ALL_NK_cluster_withNewMetadata.Rds"
  out: "/home/rstudio/mnt_out/NK_project/"
  GO_db: "/home/rstudio/mnt_resources/GSEA_GeneSetEnrichments/"
  markers: "/home/rstudio/mnt_resources/MES_ADRN/"
  metadata: "/home/rstudio/scRNA.NB.integration/metadata/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      tidy = TRUE, 
                      error = FALSE, 
                      messages = FALSE,
                      warning = FALSE)

library(parallel)
future::plan(strategy = 'future::multicore', workers = 80)
options(future.globals.maxSize = 80 * 10^9)

print(params)
```

```{r load project specific R packages and color code}
source("/home/rstudio/NK-NB_study/code/00_NK_paper_setup.R")
source("/home/rstudio/NK-NB_study/code/00_NK_paper_utils.R")
```

# ___Input_data___

```{r}
#fetahu2023 <- readRDS(file = params$input_scRNA)
ALL_NK <- readRDS(file = params$input_NK)
crinier2021 <- readRDS(file = params$input_BM1)
```

```{r}
ALL_NK <- 
  ALL_NK %>% 
  NormalizeData(normalization.method = "LogNormalize",
                scale.factor = 10000)

crinier2021 <- 
  crinier2021 %>% 
  NormalizeData(normalization.method = "LogNormalize",
                scale.factor = 10000)

# Crinier et al., 2021 as reference
NK_clusters <- crinier2021$final_clustering
original_clusters <- ALL_NK$orig.ident

fetahu2023_NK_mat <- GetAssayData(ALL_NK, 
                        assay = "RNA", 
                        slot = "data")

crinier2021_mat <- GetAssayData(crinier2021, 
                            assay = "RNA", 
                            slot = "data")
```

```{r}
# Store de.n values [Number of DE genes] from 5 to 500 with a 10 step increment
de_n_values <- seq(5, 500, by=10) 

# store results
results <- data.frame(de_n = integer(), cluster = character(), num_cells = integer())

# Loop through de.n values
for (de_n in de_n_values) {
 
  # Run SingleR with the current de.n parameter
  singleR_result <- SingleR(test = fetahu2023_NK_mat, 
                            ref = crinier2021_mat, 
                            labels = NK_clusters, 
                            de.n = de_n,
                            num.threads = 30)
  
  # Get the number of cells per cluster
  cluster_counts <- table(singleR_result$labels)
  
  # Add the results to the data frame
  results <- rbind(results, data.frame(de_n = de_n, 
                                       cluster = names(cluster_counts), 
                                       num_cells = as.integer(cluster_counts)))
}

saveRDS(singleR_result, file = paste0(params$out,
                                      "Rds/Label_transfer_sensitivity_analysis_20250328.Rds"))

write.table(results, file = paste0(params$out,"tables/label_transfer_sensitivity_analysis_20250328.csv"),
            sep = "\t", quote = FALSE,row.names = FALSE)
```

```{r}
# Plot the results using ggplot2
sensitivity_analysis <- ggplot(results, aes(x = de_n, y = num_cells, color = cluster)) +
  geom_line(linewidth = 0.5) +
  geom_point(size = 1) +
  labs(title = "Number of cells per cluster vs. de.n parameter",
       x = "de.n parameter",
       y = "Number of cells per cluster") +
  theme_minimal() +  scale_color_manual(values = COLOR_CODE_v2)

sensitivity_analysis

# save as PDF
pdf(paste0(params$out,"figures/label_transfer_sensitivity_analysis_results_20250328.pdf"),
    height = 3, width = 5)
sensitivity_analysis
dev.off()
```


```{r}
# Load required libraries
library(reshape2)

#  range for de.n parameter
de_n_values <- seq(5, 500, by=10)  

# Initialize a list to store results
results_list <- list()

# Loop through de.n values
for (de_n in de_n_values) {
  
  # Run SingleR with the current de.n parameter
  singleR_result <- SingleR(test = fetahu2023_NK_mat, 
                            ref = crinier2021_mat, 
                            labels = NK_clusters, 
                            de.n = de_n,
                            num.threads = 80)
  
  # Store the results in a list, using de.n as the name
  results_list[[as.character(de_n)]] <- singleR_result$labels
}

# Convert the results list to a data frame
results_df <- do.call(cbind, results_list)
colnames(results_df) <- de_n_values
results_df <- as.data.frame(results_df)
results_df$de_n <- colnames(results_df)
results_df$Cell_ID <- rownames(results_df)

# Melt the data frame for plotting
results_melted <- melt(results_df, 
                       id.vars = "Cell_ID", 
                       variable.name = "de_n", 
                       value.name = "Predicted_Type")

results_melted

# Make sure de.n is treated as a numeric variable
results_melted$de_n <- as.numeric(as.character(results_melted$de_n))

# Plot the heatmap
params_sensitivity_heatmap_plot <- ggplot(results_melted, aes(x = de_n, 
                                                              y = Cell_ID, 
                                                              fill = Predicted_Type)) +
  geom_tile() +
  scale_fill_manual(values = COLOR_CODE_v2) +
  labs(title = "Heatmap of predicted NK sub-types across different de.n values",
       x = "de.n parameter",
       y = "Cell ID",
       fill = "Predicted NK Type") +
  theme_minimal() +
  theme(axis.text.y = element_blank(),  # Optional: Hide y-axis text if there are too many cells
        axis.ticks.y = element_blank(),
        panel.grid = element_blank())


write.table(results_df, file = paste0(params$out,"tables/label_transfer_sensitivity_analysis_per_cell_ID_20250328.csv"),
            sep = "\t")
```

```{r}
params_sensitivity_heatmap_plot

pdf(params$out,"figures/label_transfer_heatmap_plot_20250328.pdf")
params_sensitivity_heatmap_plot
dev.off()
```

```{r subsampled}
set.seed(123)
num_cells <- nrow(results_df)

# If the number of cells is greater than 500, sub-sample
if (num_cells > 500) {
  # Randomly sample 500 cell IDs
  sampled_cell_ids <- sample(results_df$Cell_ID, 500, replace = FALSE)
  
  # Subset results_df to include only the sampled cells
  results_df_subsampled <- results_df[results_df$Cell_ID %in% sampled_cell_ids, ]
} else {
  # If there are fewer than 500 cells, use the entire dataset
  results_df_subsampled <- results_df
  warning("The number of cells is less than or equal to 500; using the entire dataset.")
}

# Display the first few rows of the subsampled data frame
head(results_df_subsampled)

# Melt the data frame for plotting
df_subsampled_melted <- melt(results_df_subsampled, 
                       id.vars = "Cell_ID", 
                       variable.name = "de_n", 
                       value.name = "Predicted_Type")

df_subsampled_melted

# Make sure de.n is treated as a numeric variable
df_subsampled_melted$de_n <- as.numeric(as.character(df_subsampled_melted$de_n))

# Plot the heatmap

params_sensitivity_plot <- ggplot(df_subsampled_melted, 
                                  aes(x = de_n, y = Cell_ID, fill = Predicted_Type)) +
  geom_tile() +
  scale_fill_manual(values = COLOR_CODE_v2) +
  labs(title = "Heatmap of predicted NK sub-types across different de.n values",
       x = "de.n parameter",
       y = "Cell ID",
       fill = "Predicted NK Type") +
  theme_minimal() +
  theme(axis.text.y = element_blank(),  # Optional: Hide y-axis text if there are too many cells
        axis.ticks.y = element_blank(),
        panel.grid = element_blank())
```

```{r}
params_sensitivity_plot

pdf(params$out,"figures/label_transfer_sensitivity_analysis_v2_20250328.pdf")
params_sensitivity_plot
dev.off()
```


