---
title: "NK project: Paper figures"
author: "Dr. Sara Wernig-Zorc"
date: "12.09.2024 - "
output: 
  html_document: 
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: false
    code_folding: hide
    highlight: pygments
    theme: spacelab
    df_print: paged
params:
  input_BM1: "/home/rstudio/mnt_data/BM/crinier2021/Rds/scBM_healthy_seurat_v4.Rds"
  input_BM2: "/home/rstudio/mnt_data/BM/yang2019/Rds/Human_BM_NK_seurat_v4.Rds"
  input_BM3: "/home/rstudio/mnt_data/BM/Lee/disco_bone_marrow_v2.0.rds"
  input_scRNA: "/home/rstudio/mnt_out/scRNA-seq_stage_M/results/published/data/rna_decontaminated.rds"
  out: "/home/rstudio/mnt_out/NK_project/"
  GO_db: "/home/rstudio/mnt_resources/GSEA_GeneSetEnrichments/"
  markers: "/home/rstudio/mnt_resources/MES_ADRN/"
  metadata: "/home/rstudio/scRNA.NB.integration/metadata/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      tidy = TRUE, 
                      error = FALSE, 
                      messages = FALSE,
                      warning = FALSE)

library(parallel)
future::plan(strategy = 'future::multicore', workers = 80)
options(future.globals.maxSize = 80 * 10^9)
options(Seurat.object.assay.version = "v5")
print(params)
```

```{r load project specific R packages and color code}
source("/home/rstudio/scRNA.scATAC/R/00_NK_paper_setup.R")
source("/home/rstudio/scRNA.scATAC/R/00_NK_paper_utils.R")
```

# ___Input_data___

```{r}
fetahu2023 <- readRDS(file = paste0(params$out,"Rds/fetahu2023_withMetadata.Rds"))
ALL_NK <-  readRDS(file = paste0(params$out,"Rds/fetahu2023_NK_subclusters_from_Crinier2021_de.n=350.Rds"))
crinier2021 <- readRDS(file = paste0(params$input_BM1))

crinier2021$cohort <- "adult"
ALL_NK$cohort <- "child"

# sample/batch information with the same variable name
ALL_NK$batch <- ALL_NK$patients 

# convert a v4 assay to a v5 assay
ALL_NK[["RNA"]] <- as(object = ALL_NK[["RNA"]], 
                      Class = "Assay5")

crinier2021[["RNA"]] <- as(object = crinier2021[["RNA"]], 
                           Class = "Assay5")

ALL_NK@meta.data$case_control <- NA
ALL_NK@meta.data <- ALL_NK@meta.data %>% 
  mutate(case_control = ifelse(ALL_NK$disease == "GNB", "CTRL",
                        ifelse(ALL_NK$disease == "GNM", "CTRL", "NB")))

ALL_NK@meta.data$case_control <- factor(ALL_NK@meta.data$case_control)
ALL_NK@meta.data$case_control <- droplevels(ALL_NK@meta.data$case_control)

# 1. Change to the new group identitites
Idents(ALL_NK) <- ALL_NK@meta.data$case_control

#2. Scale and normalize read counts for plotting
ALL_NK <- ALL_NK %>% NormalizeData(normalization.method = "LogNormalize",
                scale.factor = 10000) %>% ScaleData()

fetahu2023 <- fetahu2023 %>% 
  NormalizeData(normalization.method = "LogNormalize",
                scale.factor = 10000) %>% 
  ScaleData()
```

# ___Figure 1, B___

```{r fig.height=5, fig.width=5}
SCpubr::do_DimPlot(fetahu2023,
                                 border.color = NA,
                                 plot_cell_borders = FALSE,
                                 reduction = "UMAP",
                                 colors.use =  COLOR_CODE_UMAP,
                                 repel = TRUE,
                                 font.size = 18,
                                 label.size  = 18,
                                 plot.axes = FALSE,
                                 label = FALSE,
                                 legend.title = "Clusters",
                                 plot.title = "",
                                 legend.position = "none")
```

```{r fig.height=5, fig.width=15}
do_DimPlot(sample = ALL_NK,
           plot.title = "Fetahu et al., 2023",
           plot.subtitle = "NK cluster",
           reduction = "UMAP",
           colors.use = c("NB" = "#b4d1ee",
                          "CTRL" = "#6c77c1"),
           split.by = "case_control",
           shuffle = TRUE,
           repel = TRUE,
           plot_density_contour = FALSE,
           label.size = 16,
           font.size = 14,
           plot.axes = TRUE,
           pt.size = 0.5,
           legend.title = "Clusters",
           legend.position = "right",
           raster.dpi = 300,
           plot_cell_borders = FALSE)
```


```{r fig.height=5, fig.width=15}
do_DimPlot(sample = ALL_NK,
           plot.title = "Fetahu et al., 2023",
           plot.subtitle = "NK cluster",
           reduction = "UMAP",
           colors.use = COLOR_CODE_v2,
           split.by = "case_control",
           group.by = "predicted_NK_type_de.n350",
           shuffle = TRUE,
           repel = TRUE,
           plot_density_contour = FALSE,
           label.size = 16,
           font.size = 14,
           plot.axes = TRUE,
           pt.size = 0.5,
           legend.title = "Clusters",
           legend.position = "right",
           raster.dpi = 300,
           plot_cell_borders = FALSE)
```

```{r fig.height=8, fig.width=12}
do_DimPlot(sample = ALL_NK,
           plot.title = "Fetahu et al., 2023",
           plot.subtitle = "NK cluster",
           reduction = "UMAP",
           colors.use = COLOR_CODE_v2,
           split.by = "group.y",
           group.by = "predicted_NK_type_de.n350",
           shuffle = TRUE,
           repel = TRUE,
           plot_density_contour = FALSE,
           label.size = 16,
           font.size = 14,
           plot.axes = TRUE,
           pt.size = 0.5,
           legend.title = "Clusters",
           legend.position = "right",
           plot_cell_borders = FALSE
           )
```


# ___Figure 5, E___


```{r fig.height=5, fig.width=10}
genes.to.plot <- c("CD6","IFNG","TNF")

SCpubr::do_FeaturePlot(sample = ALL_NK,
                       reduction = "UMAP",
                       features = genes.to.plot,
                       order = TRUE,
                       label = FALSE,
                       font.size = 16,
                       pt.size = 1,
                       plot.title = "RNA expression",
                       ncol = 3,
                       number.breaks = 10,
                       #diverging.direction = -1,
                       #use_viridis = TRUE,
                       #viridis.palette = "F",
                       individual.subtitles = c("\t \t \t \t CD6", 
                                                "\t \t \t \t IFNG", 
                                                "\t \t \t \t TNF"),
                       legend.length = 10,
                       border.color = NA,
                       legend.title = "Scaled RNA expression",
                       plot.axes = TRUE,
                       slot = "scale.data",
                       min.cutoff = c(0,0,0),
                       max.cutoff = c(3,3,3)
                       )
```

## ___per sample___

```{r}
percent_NK_group <- table(ALL_NK$predicted_NK_type,
                          ALL_NK$case_control)

# Transform this data in %
data_percentage <- apply(percent_NK_group, 2, 
                         function(x){x*100/sum(x,na.rm=T)})


percent_NK_group_trans <- melt(data_percentage) 

ggplot(percent_NK_group_trans, aes(x = Var2, y = value, fill = Var1)) + 
  geom_bar(stat = "identity", position = "stack") +
  theme_void() + 
  labs(x = "", y = "Percentage of NK cells assigned to each sub-cluster", 
       fill = "NK clusters") +  
  ggtitle("Predicted NK subsets") +
  theme(axis.text.x = element_text(angle = 0, 
                                   hjust = 1,
                                   color = "black",
                                   size = 16),
        axis.text.y = element_text(angle = 0,
                                   hjust = 1,
                                   color = "black",
                                   size = 16),
        legend.text = element_text(angle = 0, 
                                   hjust = 1,
                                   color = "black",
                                   size = 18),
        axis.title.x = element_text(size = 16,
                                    color = "black",),                        
        axis.title.y = element_text(size = 16,
                                    angle = 90,
                                    color = "black",),                 
        legend.title = element_text(size = 16,
                                    color = "black"),
        title = element_text(size = 20,
                                    color = "black")) +
  scale_fill_manual(values = COLOR_CODE_v2)
```

## ___per group___

```{r}
ggplot(percent_NK_group_trans, aes(x = Var2, y = value, fill = Var1)) + 
  geom_bar(stat = "identity", position = "stack") +
  theme_void() + 
  labs(x = "", y = "Percentage of NK cells assigned to each sub-cluster", 
       fill = "NK clusters") +  
  ggtitle("Clustered Stacked Bar Plot of NK Groups") +
  theme(axis.text.x = element_text(angle = 0, 
                                   color = "black",
                                   size = 16),
        axis.text.y = element_text(angle = 0, 
                                   hjust = 1,
                                   color = "black",
                                   size = 16),
        legend.text = element_text(angle = 0, 
                                   hjust = 1,
                                   color = "black",
                                   size = 18),
        axis.title.x = element_text(size = 16,
                                    color = "black",),                        
        axis.title.y = element_text(size = 16,
                                    color = "black",),                 
        legend.title = element_text(size = 16,
                                    color = "black"),
        title = element_text(size = 20,
                                    color = "black")) +
  scale_fill_manual(values = COLOR_CODE_v2)
        
```

# ___Figure 3, E___

ALCAM expression per sample

```{r}
do_ViolinPlot(fetahu2023,features = "ALCAM",
              group.by = "sample",
              colors.use = COLOR_CODE_PATIENTS,
              slot = "scale.data",
              assay = "RNA",
              plot.grid = FALSE,
              plot_boxplot = FALSE,
              legend.position = "right",
              grid.type = "blank",
              ylab = "patients",share.y.lims = TRUE
              )

VlnPlot(fetahu2023,features = "ALCAM",
              group.by = "sample",cols = COLOR_CODE_PATIENTS)
```

# ___Figure 3, E___


```{r}
nb_metadata <- readRDS("/home/rstudio/mnt_out/scRNA-seq_stage_M/results/published/data/metadata.rds")

nb <-
  readRDS("/home/rstudio/mnt_out/scRNA-seq_stage_M/results/published/data/rna_decontaminated.rds") %>% 
  logNormCounts(assay.type = "soupx_counts")
colData(nb) <-
  nb_metadata %>%
  mutate(Size_Factor = colData(nb)$Size_Factor) %>% 
  column_to_rownames("cell") %>% 
  as("DataFrame")
rowData(nb)[["gene_short_name"]] <- rownames(nb)
```

```{r}
do_ViolinPlot(fetahu2023,features = "ALCAM",
              group.by = "sample",
              colors.use = COLOR_CODE_PATIENTS,
              slot = "scale.data",
              assay = "RNA",
              plot.grid = FALSE,
              plot_boxplot = FALSE,
              legend.position = "right",
              grid.type = "blank",
              ylab = "patients",
              share.y.lims = TRUE
              )
```

```{r}
make_matrix <- function(gene, cell_type) {
  metadata <- 
    cellchat@meta %>% 
    as_tibble(rownames = "cell")
  
  barcodes <- 
    metadata %>% 
    filter(cellont_abbr == {{cell_type}}) %>% 
    pull(cell)
  
  cellchat@data.signaling[gene, barcodes, drop = FALSE] %>%
    t() %>%
    as.matrix() %>%
    magrittr::set_colnames("logexp") %>%
    as_tibble(rownames = "cell") %>%
    left_join(metadata, by = "cell") %>%
    transmute(
      gene = gene,
      cell_type = cell_type,
      sample = rename_patients(sample),
      group = rename_groups(group),
      logexp = logexp / max(logexp)
    )
}

plot_violin <- function(genes, cell_types, y_axis_pos = "left",
                        sample_order = NULL, font_size = 18, color_scheme = NULL) {
  plot_data <-
    list(gene = genes, cell_type = cell_types) %>%
    cross_df() %>%
    pmap_dfr(make_matrix) %>%
    mutate(gene = as_factor(gene), cell_type = as_factor(cell_type))
  
  # Set y-axis position
  if (y_axis_pos == "left") {
    switch <- "y"
    position <- "left"
  } else {
    switch <- NULL
    position <- "right"
  }
  
  # If sample_order is provided, use it to reorder the samples
  if (!is.null(sample_order)) {
    plot_data$sample <- factor(plot_data$sample, levels = sample_order)
  } else {
    # Default sample order (PATIENT_ORDER)
    plot_data$sample <- factor(plot_data$sample, levels = PATIENT_ORDER)
  }

  # Rename samples using PATIENTS_RENAME mapping
  plot_data$sample <- recode(plot_data$sample, !!!PATIENTS_RENAME)

  # If no custom color scheme is provided, use the default GROUP_COLORS
  if (is.null(color_scheme)) {
    color_scheme <- GROUP_COLORS
  }

  # Generate the violin plot
  ggplot(plot_data, aes(x = sample, y = logexp, color = sample, fill = sample)) +
    geom_violin(
      size = BASE_LINE_SIZE,
      scale = "width",
      width = 0.4,
      show.legend = FALSE
    ) +
    stat_summary(geom = "point", fun = mean, size = .2) +
    xlab("patient") +
    scale_y_continuous(
      "log-normalized expression of gene",
      limits = c(0, 1),
      position = position
    ) +
    scale_fill_manual(values = color_scheme) +  # Set fill colors based on color_scheme
    scale_color_manual(values = color_scheme) + # Set border (color) based on color_scheme
    facet_grid(
      vars(gene),
      vars(cell_type),
      scales = "free_x",
      space = "free_x",
      switch = switch
    ) +
    theme_nb(grid = FALSE) +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.y.right = element_text(margin = margin(l = 6.75, unit = "pt")),
      strip.placement = "outside",
      strip.switch.pad.grid = unit(0, "mm"),
      text = element_text(size = font_size)  # Set font size for the entire plot
    )
}

```

### ___ALCAM expression on tumor cells___

```{r}
# Call the function with custom colors and a custom sample order
plot_violin(
  genes = "ALCAM", 
  cell_types = "NB", 
  sample_order = PATIENT_ORDER,
  font_size = 40,  
  color_scheme = COLOR_CODE_PATIENTS_GROUP  
)

ggsave(filename = paste0(params$out,"figures/ALCAM_violinplot.png"),dpi = 2000)
```


### ___CD6 expression on NK cells___

```{r}
plot_violin(
  genes = "CD6", 
  cell_types = "NK", 
  sample_order = PATIENT_ORDER,
  font_size = 40,  
  color_scheme = COLOR_CODE_PATIENTS_GROUP  
)

```

#### ___CD6 expression on NK subclusters, per group___

```{r}
Idents(ALL_NK) <- ALL_NK@meta.data$predicted_NK_type_de.n350

# identify cell IDs associated with each cluster
cluster1 <- WhichCells(ALL_NK, ident = "hNK_Bm1")
cluster2 <- WhichCells(ALL_NK, ident = "hNK_Bm2")
cluster3 <- WhichCells(ALL_NK, ident = "hNK_Bm3")
cluster4 <- WhichCells(ALL_NK, ident = "hNK_Bm4")


ALL_NK@active.ident <- ALL_NK$orig.ident

# re-label the NK cells to the corresponding predicted sub-clusters 
Idents(object = ALL_NK, cells = cluster1) <- "NK (hNK_Bm1)"
Idents(object = ALL_NK, cells = cluster2) <- "NK (hNK_Bm2)"
Idents(object = ALL_NK, cells = cluster3) <- "NK (hNK_Bm3)"
Idents(object = ALL_NK, cells = cluster4) <- "NK (hNK_Bm4)"

ALL_NK@meta.data

# Add active identities to metadata column new_clusters
ALL_NK$new_cell_annotation <- ALL_NK@active.ident
```

```{r}
make_matrix <- function(gene, cell_type) {
  metadata <- 
    ALL_NK@meta.data %>% 
    as_tibble(rownames = "cell")
  
  barcodes <- 
    metadata %>% 
    filter(new_cell_annotation == {{cell_type}}) %>% 
    pull(cell)
  
  cellchat@data.signaling[gene, barcodes, drop = FALSE] %>%
    t() %>%
    as.matrix() %>%
    magrittr::set_colnames("logexp") %>%
    as_tibble(rownames = "cell") %>%
    left_join(metadata, by = "cell") %>%
    transmute(
      gene = gene,
      cell_type = cell_type,
      sample = rename_patients(sample),
      group = rename_groups(group),
      logexp = logexp / max(logexp)
    )
}

plot_violin <- function(genes, cell_types, y_axis_pos = "left", font_size = 18,
                        sample_order = NULL, color_scheme = NULL) {
  plot_data <-
    list(gene = genes, cell_type = cell_types) %>%
    cross_df() %>%
    pmap_dfr(make_matrix) %>%
    mutate(gene = as_factor(gene), cell_type = as_factor(cell_type))
  
  # Set y-axis position
  if (y_axis_pos == "left") {
    switch <- "y"
    position <- "left"
  } else {
    switch <- NULL
    position <- "right"
  }
  
  # If sample_order is provided, use it to reorder the samples
  if (!is.null(sample_order)) {
    plot_data$sample <- factor(plot_data$sample, levels = sample_order)
  } else {
    # Default sample order (PATIENT_ORDER)
    plot_data$sample <- factor(plot_data$sample, levels = PATIENT_ORDER)
  }

  # Rename samples using PATIENTS_RENAME mapping
  plot_data$sample <- recode(plot_data$sample, !!!PATIENTS_RENAME)

  # If no custom color scheme is provided, use the default GROUP_COLORS
  if (is.null(color_scheme)) {
    color_scheme <- GROUP_COLORS
  }

  # Generate the violin plot
  ggplot(plot_data, aes(x = sample, y = logexp, color = sample, fill = sample)) +
    geom_violin(
      size = BASE_LINE_SIZE,
      scale = "width",
      width = 0.4,
      show.legend = FALSE
    ) +
    stat_summary(geom = "point", fun = mean, size = .2) +
    xlab("patient") +
    scale_y_continuous(
      "log-normalized expression of gene",
      limits = c(0, 1),
      position = position
    ) +
    scale_fill_manual(values = color_scheme) +  # Set fill colors based on color_scheme
    scale_color_manual(values = color_scheme) + # Set border (color) based on color_scheme
    facet_grid(
      vars(gene),
      vars(cell_type),
      scales = "free_x",
      space = "free_x",
      switch = switch
    ) +
    theme_nb(grid = FALSE) +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.y.right = element_text(margin = margin(l = 6.75, unit = "pt")),
      strip.placement = "outside",
      strip.switch.pad.grid = unit(0, "mm"),
      text = element_text(size = font_size)  # Set font size for the entire plot
    )
}

```


```{r eval=FALSE, include=FALSE}
plot_violin(
  genes = "CD6", 
  cell_types = "NK", 
  sample_order = PATIENT_ORDER,
  font_size = 40,  
  color_scheme = PATIENT_COLORS  
)

ggsave(filename = paste0(params$out,"figures/CD6_violinplots_NKsubsets_perGroup.png"),
       dpi = 2000)

```

# ___Figure 5, C___

```{r}
Idents(ALL_NK) <- ALL_NK@meta.data$group.y

# Subset by group
MNA_NK <- subset(ALL_NK, ident = "MNA")
ATRX_NK <- subset(ALL_NK, ident = "ATRXdel")
SPR_NK <- subset(ALL_NK, ident = "sporadic")
CTRL_NK <- subset(ALL_NK, ident = "control")

# Gene list
secreted_factors <- c("IFNG","TNF","CCL5")
secreted_factors <- c("IFNG","TNF")
```
## ___ALL___

```{r fig.height=5, fig.width=6}
do_DotPlot(sample = ALL_NK,
           axis.text.x.angle = 45,
           features = secreted_factors,
           plot.title = "Secreted NK factors",
           plot.subtitle = "All groups",
           scale = TRUE,
           legend.length = 5,
           group.by = "predicted_NK_type_de.n350",
           use_viridis = TRUE,
           number.breaks = 7,
           viridis.direction = -1,
           viridis.palette = "magma",
           font.size = 18,
           dot.scale = 15,
           dot_border = FALSE, 
           legend.position = "right",
           legend.title = "Scaled RNA expression")
```

```{r fig.height=5, fig.width=6}
do_DotPlot(sample = ALL_NK,
           axis.text.x.angle = 45,
           features = secreted_factors,
           plot.title = "Secreted NK factors",
           plot.subtitle = "All groups",
           scale = TRUE,
           legend.length = 5,
           group.by = "group.y",
           use_viridis = TRUE,
           number.breaks = 7,
           viridis.direction = -1,
           viridis.palette = "magma",
           font.size = 18,
           dot.scale = 15,
           dot_border = FALSE, 
           legend.position = "right",
           legend.title = "Scaled RNA expression")
```


## ___MNA___

```{r fig.height=5, fig.width=6}
do_DotPlot(sample = MNA_NK,
           axis.text.x.angle = 45,
           features = secreted_factors,
           plot.title = "Secreted NK factors",
           plot.subtitle = "MNA",
           scale = TRUE,
           legend.length = 5,
           group.by = "predicted_NK_type_de.n350",
           use_viridis = TRUE,
           number.breaks = 7,
           viridis.direction = -1,
           viridis.palette = "magma",
           font.size = 18,
           dot.scale = 15,
           dot_border = FALSE, 
           legend.position = "right",
           legend.title = "Scaled RNA expression")
```

## ___ATRX___

```{r fig.height=5, fig.width=6}
do_DotPlot(sample = ATRX_NK,
           axis.text.x.angle = 45,
           features = secreted_factors,
           plot.title = "Secreted NK factors",
           plot.subtitle = "ATRXmut",
           scale = TRUE,
           legend.length = 5,
           number.breaks = 7,
           group.by = "predicted_NK_type_de.n350",
           use_viridis = TRUE,
           viridis.direction = -1,
           viridis.palette = "magma",
           font.size = 18,
           dot.scale = 15,
           dot_border = FALSE, 
           legend.position = "right",
           legend.title = "Scaled RNA expression")
```

## ___Sporadic___

```{r fig.height=5, fig.width=6}
do_DotPlot(sample = SPR_NK,
           axis.text.x.angle = 45,
           features = secreted_factors,
           plot.title = "Secreted NK factors",
           plot.subtitle = "Sporadic",
           scale = TRUE,
           legend.length = 5,
           group.by = "predicted_NK_type_de.n350",
           use_viridis = TRUE,
           number.breaks = 7,
           viridis.direction = -1,
           viridis.palette = "magma",
           font.size = 18,
           dot.scale = 15,
           dot_border = FALSE, 
           legend.position = "right",
           legend.title = "Scaled RNA expression")
```


## ___CTRL___

```{r fig.height=5, fig.width=6}
do_DotPlot(sample = CTRL_NK,
           axis.text.x.angle = 45,
           features = secreted_factors,
           plot.title = "Secreted NK factors",
           plot.subtitle = "Control",
           scale = TRUE,
           legend.length = 5,
           number.breaks = 7,
           group.by = "predicted_NK_type_de.n350",
           use_viridis = TRUE,
           viridis.direction = -1,
           viridis.palette = "magma",
           font.size = 18,
           dot.scale = 15,
           dot_border = FALSE, 
           legend.position = "right",
           legend.title = "Scaled RNA expression")
```

# ___THE END___

```{r}
sessionInfo()
```

