project_name: single_cell
project_docker: swernig/single_cell_env:v1.0

# PATHS AS VISIBLE WITHIN RSTUDIO:
project_root: /home/rstudio/
resource_root: /home/rstudio/mnt_resources
data_root: /home/rstudio/mnt_data
out_root: /home/rstudio/mnt_out
tmp_root: /home/rstudio/mnt_tmp


# access to local folders:
project_root_host: /home/$USER/bioinf_isilon/Research/HALBRITTER/zHalbritter_TaschnerMandl/wernig-zorc.sara/code/
resource_root_host: /home/$USER/bioinf_isilon/Research/HALBRITTER/zHalbritter_TaschnerMandl/wernig-zorc.sara/resources/
data_root_host: /home/$USER/bioinf_isilon/Research/HALBRITTER/zHalbritter_TaschnerMandl/wernig-zorc.sara/data/
out_root_host: /home/$USER/bioinf_isilon/Research/HALBRITTER/zHalbritter_TaschnerMandl/wernig-zorc.sara/out/
tmp_root_host: /scratch/research/halbritter/$USER/

# PROJECT CONFIG:
genome_build: hg38
genome_RNA: 10xGenomics/refdata-gex-GRCh38-2024-A
genom_fixed_RNA: 10xGenomics/fixed_scRNA_probes/
genome_chromatin: 10xGenomics/cellranger-atac-2.1.0
gtf: 10xGenomics/refdata-gex-GRCh38-2024-A/genes/genes.gtf

# Multithreading parameters
n_threads_max: 64
NUM_THREADS: 40
N_CORES: 20


